version: '3'

tasks:
  generate:
    aliases:
      - "gen"
    desc: "Generate code from proto"
    cmds:
      - "protoc -I ./proto -I ./proto/google/api --go_out=./auth-service/internal/delivery/gRPC --go_opt=paths=source_relative --go-grpc_out=./auth-service/internal/delivery/gRPC --go-grpc_opt=paths=source_relative --grpc-gateway_out=./auth-service/internal/delivery/gRPC --grpc-gateway_opt=paths=source_relative ./proto/auth.proto"
