routes:
  - name: "forum-service"
    path: "/api/v1/forum/**"
    target: "http://forum-service:8080"
    methods: ["GET", "POST", "PUT", "DELETE"]
    auth_required: true
    roles: ["user", "admin"]

  - name: "auth-service"
    path: "/api/v1/auth/**"
    target: "http://auth-service:50051"
    methods: ["POST"]
    auth_required: false